language: java
jdk: openjdk8
node_js: "10"
before_install:
  - cd client
  - npm install
  - npm run build
  - cd ..
before_script:
  - cd client
  - npm run test
  - cd ..
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.npm
    - client/node_modules