language: java
jdk: openjdk8

env:
  - REACT_APP_VERSION="$TRAVIS_BUILD_NUMBER.$TRAVIS_COMMIT"

before_install:
  - cd client
  - nvm install
  - npm ci
  - npm run build
  - cd ..

before_script:
  - cd client
  - npm run test
  - cd ..

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.npm

#notifications:
#  slack:
#    rooms:
#      - secure: "Icn7Vj/Qilt8hE4PXfxEDwp7OuPQXZ9+RiSDvykKPvb77m36WrKfBrvyKGmjb8mFKjXjd90tscRr7C4rIdoTXGgHYpp+07rBo3SmnwdevYKGyqMSFYqdDEtBHRZEoV7w81eO8HE6oJaFZgW/YW8jh1/oH3nJiwxTXDRBAeMF6Gfe5FiQsDcxhhf+Gzpcg0RDHadFm45LcPe22pMxel+Uav6Oc2/rTQKVj6GKET7P25ZMmNVlRzSy+2IIIo0mKxClUIdJqloGSiOU3xEw4LtWUYn0Q7dPxpBZ5G1cBw1kU2RVRjLo/fUd6VsY5aQXE8wkT1Gz0Wya0VOGIX3kDA/7vBvZWHPEOFoNROp+STh2HHx0lCre+92/HTlMYxZ0sZR6Yz03W02rb/pfDlQhSPJWO42xNsiOXq4+y6Us4KePzvUB+5EMkR7rTBUnGTD3iNSr7PC57ybuRHC7UbPXVABVVzUDG871XmpgikWq2TZPbOqfCSytARE3MUFulEq+gpA6iCbHvxO8+qg/GEb66TrADAoRulZa8bJsUsJwlHQJ9yfho4vAZzr+uF6lAXQIFSV7WFnlopVC16MU37okvfobIF84l/6uAbWGhPdvkw34EyCnckwIRFq+6j9bN2jAXxbbRz4I++ACwkiotGBpodp/Cae0YH0ZNHV39jYrXGzubv0="

before_deploy:
  # store files w/ a .yaml extension for easier editing, but EB needs .config
  - for f in .ebextensions/*.yaml; do mv $f $f.config; done
  - zip target/eb_bundle.zip -r .ebextensions
  - zip target/eb_bundle.zip -j target/cookbook-*.jar

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAYLRQLC7OYU4FNN6E"
  secret_access_key:
    secure: "pDci9bswxdNSvP/6JSfLRfjXsIClipJJUAa55AB+5UHq4IXs6qLWEz+LLJGsDr0YpBJGM9bnlY5z/iGEFLicYAJFfdxJBPpWzz3wNhhNqTIDo41MBhtfL+tmJBa3JCGM7ZLtvdrBUoO9e0HKhatDniV3UNd46sk2aYqAFPTu/kFINJTOsCZ+wk80fXItLaH5P7tNzpk36AEW2lb57yHMueIOsBpP9uvO6TkwaJLqWVO6Lnt6qg/PA4rqUAyZa30TIGXNGdv0uZHt/D7IsXMK5qT/UCr+6vBdqeRWVPJEKJR32iGce2PWd4fi5RaT1gv8BsOL8yZ3SR8T38daNFDrgzY9F3I4IwVE+t/Ja4ubqqVSP3kyoyssPnqfvR9f5XXgdVqwKyhLAKOZozZnPXK7NIivc5NBGsTLxM0qHwjjmehHTTtHftlSNdtU+qeK0BVqAToMhDroyI6jkHTbuPX8vH3JeRM7GfqPaaDoSz5sMgHdZTJ59OrrX1YaxRCDK7hMg7UCZq26E3nqc5v6or7v4H+/MsOJq7PD2lofpSz4LYz3M8zTRmRu1hSpyymKdvBEOQ04MPisJkYqtNauT5C1kfaG27QlHfmNKgnil29v3pq90Yeo9/RRHPHxBCES1vHHjtu/tWs0kn+wJEUKsLz30fzfS96WsS2wt135EVIdlSA="
  region: "us-west-2"
  app: "cookbook"
  env: "Cookbook-REST-env"
  bucket_name: "elasticbeanstalk-us-west-2-574553266141"
  skip_cleanup: true
  zip_file: target/eb_bundle.zip
  on:
    branch: master
