interface Owned {
    """The friend who owns this object."""
    owner: Friend!
    """
    Another friend who owns this object. Always null if the current user is the
    owner, always the same as `owner` otherwise.
    """
    ownedBy: Friend
    """Is the owner of this object me (the current user)?"""
    mine: Boolean!
    """Is the owner of this object not me (the current user)?"""
    notMine: Boolean!
}

interface AccessControlled implements Owned {
    owner: Friend!
    ownedBy: Friend
    mine: Boolean!
    notMine: Boolean!
    """The object's ACL, which includes its owner and any grants of access.
    """
    acl: Acl!
    grants: [AccessControlEntry!]!
}

type Acl implements Owned {
    owner: Friend!
    ownedBy: Friend
    mine: Boolean!
    notMine: Boolean!
    """Users granted access by the owner or an administrator. Conceptually,
    this is a map, so a given user (the key) uniquely identifies their access
    level (the value).
    """
    grants: [AccessControlEntry!]!
}

type AccessControlEntry {
    """The friend who has been granted access to an AccessControlled object."""
    friend: Friend!
    "DEPRECATED: use friend"
    user: Friend!
    """The level of access the user has been granted."""
    level: AccessLevel!
}

enum AccessLevel {
    VIEW
    CHANGE
    ADMINISTER
}

extend type Query {
    """DEPRECATED: prefer `profile.me`"""
    getCurrentUser: User
    profile: ProfileQuery!
}

extend type Mutation {
    profile: ProfileMutation!
}

type User implements Node {
    id: ID!
    name: String
    email: String!
    imageUrl: String
    provider: String!
    roles: [String!]!
    devices: [UserDevice!]!
    """A value for every preference is returned. If a deviceKey is provided,
    that device's values will be used. Otherwise, the user's global preferences
    are used, if they exists. If not, the static default is returned.
    """
    preferences(deviceKey: String): [UserPreference!]!
    """Return a single preference. If a deviceKey is provided, that device's
    value will be used. Otherwise, the user's global preference will be used, if
    one exists. If not, the static default is returned.
    """
    preference(name: String!, deviceKey: String): UserPreference!
    me: Boolean!
    notMe: Boolean!
}

type UserPreference {
    user: User!
    device: UserDevice
    type: DataType!
    name: String!
    value: String
}

type UserDevice implements Node {
    id: ID!
    user: User!
    key: String!
    name: String!
    createdAt: DateTime!
    lastEnsuredAt: DateTime!
    preferences: [UserPreference!]!
}

"""A suggestion for how to interpret the always-a-String value of a preference.
Clients should be "generous" in their parsing, where possible. E.g, `BOOLEAN`
strings `"123"` and `"0"` should be treated as `true` and `false`, respectively.
"""
enum DataType {
    BOOLEAN
    FLOAT
    "A string with ID semantics"
    ID
    INT
    "Arbitrary JSON-serialized data"
    JSON
    "A JSON-serialized list of ID values"
    SET_OF_IDS
    STRING
}

"""I represent an uploadable "scratch file", which may be PUT without further
authentication of the client. Scratch files are identified by their filename,
which may be passed to other APIs to "use" an uploaded scratch file.
"""
type ScratchUpload {
    """The filename which uniquely identifies the uploaded scratch file."""
    filename: String!
    """The URL to PUT the scratch file to."""
    url: String!
    """When the URL's signature will expire."""
    expiration: DateTime!
    """The content type of the scratch file."""
    contentType: String!
    """The cache-control header which must be set on the request."""
    cacheControl: String!
    """INFORMATIONAL: an example cURL command you might use to upload the file."""
    curl: String!
}

input InvitationSearch {
    status: InvitationStatus = SENT
    """How many results to return. If not specified, 5 will be returned.
    """
    first: NonNegativeInt! = 25
    """Cursor to find results after. Omit to retrieve the first page.
    """
    after: Cursor = null
}

input ReceivedInvitationSearch {
    status: InvitationStatus = SENT
    """How many results to return. If not specified, 5 will be returned.
    """
    first: NonNegativeInt! = 25
    """Cursor to find results after. Omit to retrieve the first page.
    """
    after: Cursor = null
}

"Access the current user's profile information"
type ProfileQuery {
    "My user info."
    me: User!
    "My friends."
    friends: [Friend!]!
    friendCount: NonNegativeInt!
    "Search invitations I have sent."
    sentInvitations(search: InvitationSearch!): [Invitation!]!
    "Search invitations I have received."
    receivedInvitations(search: ReceivedInvitationSearch!): [Invitation!]!
    """Request a pre-signed upload URL to PUT a scratch file to, identified by
    the returned `filename`. Upload URLs are valid for only a short time; they
    should be requested when an upload is needed, not preemptively in case one
    may be needed in the future.
    """
    scratchFile(contentType: String!, originalFilename: String): ScratchUpload!
}

type ReceivedInvitation implements Node {
    id: ID!
    "Friend this invitation came from."
    from: Friend!
    "Status of the invitation."
    status: ReceivedInvitationStatus!
    """Grant to receive upon acceptance of the invitation. If an invitation has
    no grant, it will only create a friendship.
    """
    grant: InvitationGrant
}

enum ReceivedInvitationStatus {
    SENT
    ACCEPTED
    DECLINED
}

type Invitation implements Node {
    id: ID!
    createdAt: DateTime!
    """Link to send someone so they can respond to the invitation, or empty if
    responses are no longer allowed.
    """
    link: String!
    """The secret code for the invitation. Can be used to re-group multiple
    invitations which resulted from the same invitation request.
    """
    secretCode: String!
    """Friend this invitation was sent to. May be null while `SENT` or
    `WITHDRAWN`, always non-null if `ACCEPTED` or `DECLINED`.
    """
    to: Friend
    status: InvitationStatus!
    """Grant to issue upon acceptance of the invitation. If an invitation has no
    grant, it will only create a friendship.
    """
    grant: InvitationGrant
    "Maximum number of responses this invitation accepts, one by default."
    responseLimit: NonNegativeInt!
    "Number of responses this invitation has received."
    responseCount: NonNegativeInt!
    expiresAt: DateTime!
}

enum InvitationStatus {
    SENT
    ACCEPTED
    DECLINED
    WITHDRAWN
    EXPIRED
}

type InvitationGrant {
    nodeId: ID!
    level: AccessLevel!
}

type Friend implements Node {
    id: ID!
    name: String
    email: String!
    imageUrl: String
}

type ProfileMutation {
    clearPreference(name: String!, deviceKey: String): UserPreference!
    deleteDevice(id: ID!): Deletion!
    renameDevice(id: ID!, name: String!): UserDevice!
    setPreference(name: String!, deviceKey: String, value: String!): UserPreference!
    """Create a new invitation code to establish friendship between your account
    and theirs. By default, an invitation only creates friendship and can only
    be used once (by any user). Pass a request for futher control.
    """
    createInvitation(request: InvitationRequest): Invitation!
    """Withdraw the given invitation code you created, preventing others from
    accepting it.
    """
    withdrawInvitation(id: ID!): Invitation
    """Accept an invitation you've received, establishing friendship and/or
    receiving a grant.
    """
    acceptInvitation(id: ID!): ReceivedInvitation
    """Decline an invitation you've received.
    """
    declineInvitation(id: ID!): ReceivedInvitation
    """Break your friendship with another user, revoking all grants either of
    you were issued by the other.
    """
    unfriend(id: ID!): Deletion!
}

input InvitationRequest {
    """Optionally, allow multiple recipients accept this invitation, all using
    the same secret code. Cannot be specified with `friendId`.
    """
    responseLimit: NonNegativeInt!
    """Optionally, tie this invitation to a specific friend, rather than letting
    anyone accept it. Cannot be specified with `responseLimit`.
    """
    friendId: ID
    """One or more grants to issue to each friend who accepts this invitation.
    """
    grant: [GrantRequest]
}

input GrantRequest {
    nodeId: ID!
    level: AccessLevel!
}
