name: CI (non-master)

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn --batch-mode --update-snapshots verify
