name: CI

on:
  pull_request:
    branches:
      - master
      - beta
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw --batch-mode --update-snapshots verify
